[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cq_cli"
version = "2.3.0"
license = {file = "LICENSE"}
authors = [
  { name="Jeremy Wright" },
]
description = "Command Line Interface for executing CadQuery scripts and converting their output to another format."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  'cadquery >= 2.3.1',
]

[project.optional-dependencies]
dev = [
  "black==19.10b0",
  "click==8.0.4"
]

[project.urls]
"Homepage" = "https://github.com/CadQuery/cq-cli"
"Bug Tracker" = "https://github.com/CadQuery/cq-cli/issues"
