[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cq_cli"
version = "2.3.0"
license = {file = "LICENSE"}
authors = [
  { name="Jeremy Wright" },
]
description = "Command Line Interface for executing CadQuery scripts and converting their output to another format."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "cadquery @ git+https://github.com/CadQuery/cadquery.git",
  "cadquery-ocp>=7.7.0a0,<7.8",
  "ezdxf",
  "multimethod>=1.7,<2.0",
  "numpy<2.0.0",
  "nlopt",
  "typish",
  "casadi",
  "path",
  "cadquery-freecad-import-plugin @ https://github.com/jmwright/cadquery-freecad-import-plugin.git"
]

[project.scripts]
cq-cli = "cq_cli.main:main"

[project.optional-dependencies]
dev = [
  "pytest",
  "black==19.10b0",
  "click==8.0.4"
]

[project.urls]
"Homepage" = "https://github.com/CadQuery/cq-cli"
"Bug Tracker" = "https://github.com/CadQuery/cq-cli/issues"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/cq_cli"]
