name: check-pr-commit
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'cq-cli_pyinstaller.spec'
      - '.github/workflows/pyinstaller-builds-actions.yml'
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install CadQuery and pytest
        shell: bash --login {0}
        run: |
          # conda info
          pip install --upgrade pip
          pip install --pre git+https://github.com/CadQuery/cadquery.git
          pip install pytest
      - name: Run tests
        shell: bash --login {0}
        run: |
          pytest -v
  run-pytest-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install CadQuery and pytest
        shell: bash --login {0}
        run: |
          python3 -m ensurepip
          pip3 install --upgrade pip
          pip3 install --pre git+https://github.com/CadQuery/cadquery.git
          pip3 install pytest
      - name: Run tests
        shell: bash --login {0}
        run: |
          pytest -v
  run-pytest-win:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install CadQuery and pytest
        shell: pwsh
        run: |
          pip install --upgrade pip
          pip install --pre git+https://github.com/CadQuery/cadquery.git
          pip install pytest
      - name: Run tests
        shell: pwsh
        run: |
          pytest -v
