name: check-pr-commit
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'cq-cli_pyinstaller.spec'
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: conda-incubator/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          python-version: 3.8
          activate-environment: test
      - name: Install CadQuery and pytest
        shell: bash --login {0}
        run: |
          conda info
          conda install -c cadquery -c conda-forge cadquery=master
          conda install -c anaconda pytest
      - name: Run tests
        shell: bash --login {0}
        run: |
          conda info
          pytest -v
  run-pytest-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: conda-incubator/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          python-version: 3.8
          activate-environment: test
      - name: Install CadQuery and pytest
        shell: bash --login {0}
        run: |
          conda info
          conda install -c cadquery -c conda-forge cadquery=master
          conda install -c anaconda pytest
      - name: Run tests
        shell: bash --login {0}
        run: |
          conda info
          pytest -v
  run-pytest-win:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: conda-incubator/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          python-version: 3.8
          activate-environment: test
      - name: Install CadQuery and pytest
        shell: pwsh
        run: |
          conda info
          conda install -c cadquery -c conda-forge cadquery=master
          conda install -c anaconda pytest
      - name: Run tests
        shell: pwsh
        run: |
          conda info 
          pytest -v
