name: lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-black-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Install CadQuery and pytest
        shell: bash --login {0}
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install -e .[dev]
      - name: Run tests
        shell: bash --login {0}
        run: |
          black --diff --check .
