name: pyinstaller-build
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Whether to build a single file (onefile) or directory (dir) dist'
        required: true
        default: 'dir'
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip --version
        pip install -e .
        pip install pyinstaller
        pip install path
    - name: Run PyInstaller build
      run: |
        pyinstaller pyinstaller.spec ${{ github.event.inputs.type }}
    - uses: actions/upload-artifact@v2
      with:
        name: cq-cli-Linux-x86_64
        path: dist
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip --version
        pip install -e .
        pip install pyinstaller
        pip install path
    - name: Run PyInstaller build
      run: |
        pyinstaller pyinstaller.spec ${{ github.event.inputs.type }}
    - uses: actions/upload-artifact@v2
      with:
        name: cq-cli-MacOS
        path: dist
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip --version
        pip install -e .
        pip install pyinstaller
        pip install path
    - name: Run build
      run: |
        # Get-ChildItem -Path C:\ -Filter libcasadi.dll -Recurse
        # CPATH=$pythonLocation/include/python${{ matrix.python-version }}m
        # echo "CPATH=$CPATH" >> $GITHUB_ENV
        pyinstaller pyinstaller.spec ${{ github.event.inputs.type }}
    - uses: actions/upload-artifact@v2
      with:
        name: cq-cli-Windows
        path: dist
