name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-pytest-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install CadQuery and pytest
        run: |
          pip install -e .
          pip install -e .[dev]
      - name: Run tests
        run: |
          pytest -v
