name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install CadQuery and pytest
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install -e .[dev]
        shell: bash {0}
      - name: Run tests
        run: |
          pytest -v
        shell: bash {0}
