name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-22.04]  # windows-latest , macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Dependencies (Linux)
        run: sudo apt-get update && sudo apt install -y libgl1-mesa-glx
        if: matrix.os == 'ubuntu-22.04'
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install CadQuery and pytest
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install -e .[dev]
      - name: Run tests
        run: |
          python -m pytest -v --ignore=tests/test_freecad.py
