name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-pytest-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Install CadQuery and pytest
        shell: bash --login {0}
        run: |
          pip install -e .
          pip install pytest
      - name: Run tests
        shell: bash --login {0}
        run: |
          pytest -v
      