name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-22.04]  # windows-latest , macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Dependencies (Linux)
        run: sudo apt-get update && sudo apt install -y libgl1-mesa-glx
        if: matrix.os == 'ubuntu-20.04'
      - uses: actions/checkout@v2
      - name: Install CadQuery and pytest
        run: |
          pip3 install --upgrade pip
          pip3 install -e .
          pip3 install -e .[dev]
      - name: Run tests
        run: |
          python3 -m pytest -v --ignore=tests/test_freecad.py
