name: Test FreeCAD

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install and Test
        run: |
          conda create -y -n freecad -c conda-forge python=3.11 freecad=0.21.2
          conda init bash
          source /usr/share/miniconda/bin/activate
          conda activate freecad
          python -m pip install --upgrade pip
          unset CONDA_PREFIX_1
          pip install -e .
          pip install -e .[dev]
          python -m pytest -v tests/test_freecad.py